n = input('INPUT SOMETHING: ')
s = type(n)
print(s)
print('É alphametico? {}'.format(n.isalpha()))
print('É um número? {}'.format(n.isnumeric()))
print('É alphanumerico? {}'.format(n.isalnum()))
print('É minusculo? {}'.format(n.islower()))
print('É maiusculo? {}'.format(n.isupper()))
print('É capitalizado? {}'.format(n.istitle()))